function [BW,maskedRGBImage] = createMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 01-Feb-2023
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2lab(RGB);
I = imgaussfilt(I,2);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 2.193;
channel1Max = 23.941;

% Define thresholds for channel 2 based on histogram settings
channel2Min = -14.641;
channel2Max = 10.665;

% Define thresholds for channel 3 based on histogram settings
channel3Min = -64.103;
channel3Max = 53.230;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

se = strel("disk",5);
maskedRGBImage = imopen(maskedRGBImage,se);

se = strel("square",15);
maskedRGBImage = imdilate(maskedRGBImage,se);

end
